routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/begin', function () {
    return view('begin');
});

// Route::get('/materia/index', function () {
//     return view('materias.materiaIndex');
// });

// Route::get('/materia/create', function () {
//     return view('materias.materiaForm');
// });

// Route::post('/materia/store', function () {
// //     return view('materias.materiaIndex');
// });

// Route::get('/materia/show/{id}', function ($id) {
// //     dd($id);
//     return view('materias.materiaShow',compact('id'));
// });

// Route::get('/materia/edit/{id}', function ($id) {
//     return view('materias.materiaEdit',compact('id'));
// });

// Route::post('/materia/update/{id}', function ($id) {
// //     return view('materias.materiaEdit',compact('id'));
// });
// Route::get('/materias','MateriaController@index');
Route::resource('materia','MateriaController')->parameters([
    'materia' => 'materia'
]);
Route::get('/alumno/{alumno}/register','AlumnoController@register');
Route::post('/alumno/{alumno}/materia','AttachAlumnoMateriaController@asociarAlumnoMateria');
Route::resource('/alumno','AlumnoController');
Route::resource('/user','UserController');


// Route::resource('alumno.materia','AttachAlumnoMateriaController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');





#Route::get('/materias',function(){return view('materias.materiaIndex');});
#Route::get('/coso',function(){return '<h1>holamundo</h1>';});

app/Materia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Materia extends Model
{
    protected $fillable = ['crn','seccion','calendario','materia','hora_inicio','salon','user_id'];
    protected $guarded = ['id','created_at','updated_at'];
    public function user(){
      return $this->belongsTo('App\User');
    }
    public function alumno(){
      return $this->belongsToMany('App\Alumno');
    }
}

app/Http/Controllers/MateriaController.php
<?php

namespace App\Http\Controllers;

use App\Materia;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MateriaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $materias = Materia::all();
        return view('materias.materiaIndex',compact('materias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('materias.materiaForm');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'crn' => 'required|max:6|min:5',
      ]);
//       dd('nepe');
      $materia = new Materia();
      $materia->crn = $request->input('crn');
      $materia->seccion = $request->seccion;
      $materia->calendario = $request->calendario;
      $materia->materia = $request->materia;
      $materia->hora_inicio = $request->hora_inicio;
      $materia->salon = $request->salon;
      $materia->user_id = $request->user_id;
      $materia->save();
//       $request->merge(['user_id' => Auth::user()->id]);
//       Materia::create($request->all());
      
      //metodo save de guardar relacion/////////////////////
      /*$materia = new Materia($request->all());
      $ser = User::find(Auth::user()->id);
      $user->materias()->save($materia);*/
      //metodo save de guardar relacion/////////////////////
      
      
      
      
      
      return redirect()->route('materia.index');
//       return view('materias.materiaIndex');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Materia  $materia
     * @return \Illuminate\Http\Response
     */
    public function show(Materia $materia)
//     public function show(Materia $materium)
//     public function show($id)
    {
//       $materia = Materia::find($id);
      $materia->load('user');
//       dd(Auth::user()->nombre,Auth::id(),$materia->load('user'));
//       $subject = Materia::find($id);
//       dd($sbject);
//       return view('materias.materiaShow',compact('$subject'));
//       return view('materias.materiaShow')->with(['subject' => $materia]);
      return view('materias.materiaShow',compact('materia'));
//       return view('materias.materiaShow')->with(['subject' => $materia]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Materia  $materia
     * @return \Illuminate\Http\Response
     */
//     public function edit($id)
    public function edit(Materia $materia)
    {
      return view('materias.materiaForm',compact('materia'));
//       return view('materias.materiaEdit',compact('id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Materia  $materia
     * @return \Illuminate\Http\Response
     */
//     public function update(Request $request, $id)
    public function update(Request $request, Materia $materia)
    {
//       dd("adios",$materia,$request->all());
      $materia->crn = $request->input('crn');
      $materia->seccion = $request->seccion;
      $materia->calendario = $request->calendario;
      $materia->materia = $request->materia;
      $materia->hora_inicio = $request->hora_inicio;
      $materia->salon = $request->salon;
      $materia->user_id = $request->user_id;
      $materia->save();
//       dd("adios",$materia,$request->all());
      return redirect()->route('materia.show',compact('materia'));
//       return view('materias.materiaEdit',compact('id'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Materia  $materia
     * @return \Illuminate\Http\Response
     */
//     public function destroy($id)
    public function destroy(Materia $materia)
    {
//         dd("hola",$materia);
        $materia->delete();
        return redirect()->route('materia.index');
    }
}

resources/views/materias/materiaEdit.blade.php
@extends('layouts.apu')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                  Dashboard
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="form-group">
                      <label class="col-form-label" for="crn">CRN</label>
                      <input class="form-control" name="crn" type="text" placeholder="introdusca el CRN de la materia" value="{{ $subject->crn }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="seccion">Seccion</label>
                      <input class="form-control" name="seccion" type="text" placeholder="introdusca la seccion de la materia" value="{{ $subject->seccion }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="calendario">Calendario</label>
                      <input class="form-control" name="calendario" type="text" placeholder="introdusca el calendario" value="{{ $subject->calendario }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="materia">Materia</label>
                      <input class="form-control" name="materia" type="text" placeholder="introdusca la materia" value="{{ $subject->materia }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="horainicio">Hora de inicio</label>
                      <input class="form-control" name="horainicio" type="text" placeholder="introdusca el horario" value="{{ $subject->hora_inicio }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="salon">Salon</label>
                      <input class="form-control" name="salon" type="text" placeholder="introdusca el salon" value="{{ $subject->salon }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="usuario">Usuario</label>
                      <input class="form-control" name="usuario" type="text" placeholder="introdusca el usuario" value="{{ $subject->user_id }}">
                    </div>
                  <!-- <form action="/materia/store" method="post">
                    <h1>materia</h1><br>
                    <input type="text" name="materia" value="{{ $id }}">
                    <input type="submit" values="nepe">
                  </form> -->
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/materias/materiaForm.blade.php
@extends('layouts.apu')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  Dashboard
                </div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  <h1>Registro de nueva materia</h1><br>
                  @if ($errors->any())
                      <div class="alert alert-danger">
                          <ul>
                              @foreach ($errors->all() as $error)
                                  <li>{{ $error }}</li>
                              @endforeach
                          </ul>
                      </div>
                  @endif
                  @if(isset($materia))
                  {!! Form::model($materia, ['action' => ['MateriaController@update',$materia], 'method' => 'patch']) !!}
<!--                   <form action="{{ action('MateriaController@update',$materia) }}" method="post"> -->
<!--                     <input type="hidden" name="_method" value="put"> -->
                  @else
                  {!! Form::open(['action' => 'MateriaController@store']) !!}
<!--                   <form action="{{ action('MateriaController@store') }}" method="post"> -->
<!--                     {{ csrf_field() }} -->
                  @endif
                    <div class="form-group">
                      <label class="col-form-label" for="crn">CRN</label>
                      {!! Form::text('crn', null, ['class' => 'form-control', 'placeholder' => 'Escriba el nombre del crn']); !!}
                      <small class="form-text text-muted">Sus alumnos se podrán inscribir a su materia.</small>
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="seccion">Seccion</label>
                      {!! Form::text('seccion', null, ['class' => 'form-control', 'placeholder' => 'introdusca la seccion de la materia']); !!}
                      <small class="form-text text-muted">introdusca la seccion de la materia.</small>
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="calendario">Calendario</label>
                      {!! Form::text('calendario', null, ['class' => 'form-control', 'placeholder' => 'introdusca el calendario']); !!}
                      <small class="form-text text-muted">introdusca el calendario.</small>
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="materia">Materia</label>
                      {!! Form::text('materia', null, ['class' => 'form-control', 'placeholder' => 'introdusca la materia']); !!}
                      <small class="form-text text-muted">introdusca la materia.</small>
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="hora_inicio">Hora de inicio</label>
                      {!! Form::text('hora_inicio', null, ['class' => 'form-control', 'placeholder' => 'introdusca el horario']); !!}
                      <small class="form-text text-muted">introdusca el horario.</small>
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="salon">Salon</label>
                      {!! Form::text('salon', null, ['class' => 'form-control', 'placeholder' => 'introdusca el salon']); !!}
                      <small class="form-text text-muted">introdusca el salon.</small>
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="user_id">Usuario</label>
                      {!! Form::text('user_id', null, ['class' => 'form-control', 'placeholder' => 'introdusca el usuario']); !!}
                      <small class="form-text text-muted">introdusca el usuario.</small>
                    </div>
                    <div class="tile-footer">
                      <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
<!--                   </form> -->
                  {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/materias/materiaIndex.blade.php
@extends('layouts.apu')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  Dashboard
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  <h1>Que onda perros</h1>
                  <table class="table">
                    <thead>
                      <tr>
                        <td>id</td>
                        <td>crn</td>
                        <td>seccion</td>
                        <td>calendario</td>
                        <td>materia</td>
                        <td>hora_inicio</td>
                        <td>salon</td>
                        <td>user_id</td>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($materias as $materia)
                        <tr>
                          <td>
                            <a href="{{ action('MateriaController@show',$materia->id) }}" class="btn btn-success">
                              {{ $materia->id }}
                            </a>
                          </td>
                          <td>{{ $materia->crn }}</td>
                          <td>{{ $materia->seccion }}</td>
                          <td>{{ $materia->calendario }}</td>
                          <td>{{ $materia->materia }}</td>
                          <td>{{ $materia->hora_inicio }}</td>
                          <td>{{ $materia->salon }}</td>
                          <td>{{ $materia->user->id }}:{{ $materia->user->nombre }}</td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/materias/materiaShow.blade.php
@extends('layouts.apu')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                  Dashboard
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  <h1>
                    hola wey{{ $materia->id }}
                  </h1>
                    <!--<div class="form-group">
                      <label class="col-form-label" for="crn">CRN</label>
                      <input class="form-control" name="crn" type="text" placeholder="introdusca el CRN de la materia" value="{{ $materia->crn }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="seccion">Seccion</label>
                      <input class="form-control" name="seccion" type="text" placeholder="introdusca la seccion de la materia" value="{{ $materia->seccion }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="calendario">Calendario</label>
                      <input class="form-control" name="calendario" type="text" placeholder="introdusca el calendario" value="{{ $materia->calendario }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="materia">Materia</label>
                      <input class="form-control" name="materia" type="text" placeholder="introdusca la materia" value="{{ $materia->materia }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="horainicio">Hora de inicio</label>
                      <input class="form-control" name="horainicio" type="text" placeholder="introdusca el horario" value="{{ $materia->hora_inicio }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="salon">Salon</label>
                      <input class="form-control" name="salon" type="text" placeholder="introdusca el salon" value="{{ $materia->salon }}">
                    </div>
                    <div class="form-group">
                      <label class="col-form-label" for="usuario">Usuario</label>
                      <input class="form-control" name="usuario" type="text" placeholder="introdusca el usuario" value="{{ $materia->user_id }}">
                    </div>-->
                  <table class="table">
                    <thead>
                      <tr>
                        <td>id</td>
                        <td>crn</td>
                        <td>seccion</td>
                        <td>calendario</td>
                        <td>materia</td>
                        <td>hora_inicio</td>
                        <td>salon</td>
                        <td>user_id</td>
                        <td></td>
                        <td></td>
                      </tr>
                    </thead>
                    <tbody>
                        <tr>
                          <td>{{ $materia->id }}</td>
                          <td>{{ $materia->crn }}</td>
                          <td>{{ $materia->seccion }}</td>
                          <td>{{ $materia->calendario }}</td>
                          <td>{{ $materia->materia }}</td>
                          <td>{{ $materia->hora_inicio }}</td>
                          <td>{{ $materia->salon }}</td>
                          <td>{{ $materia->user->id }}:{{ $materia->user->nombre }}</td>
                          <td>
                            {!! Form::open(['action' => ['MateriaController@destroy', $materia], 'method' => 'delete']) !!}
<!--                             <form action="{{ action('MateriaController@destroy',$materia) }}" method="post"> -->
<!--                             <form action="{{ route('materia.destroy',$materia->id) }}" method="post"> -->
<!--                               <input type="hidden" name="_method" value="delete"> -->
<!--                               {{ csrf_field() }} -->
                              <input type="submit" class="btn btn-danger" value="Eliminar">
<!--                             </form> -->
                            {!! Form::close() !!}
                          </td>
                          <td>
                            <a href="{{ action('MateriaController@edit',$materia) }}" class="btn btn-info">Modificar</a>
                          </td>
                        </tr>
                    </tbody>
                  </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection